version: "3.8"

services:
    app:
        build:
            context: ./sources/php
            dockerfile: Dockerfile
            args:
                USER_ID: ${HOST_UID}
                GROUP_ID: ${HOST_GID}
        container_name: app
        networks:
            - ddd-in-laravel-skeleton
        volumes:
            - ../:/app
        command: ["php-fpm", "-F"]
        tty: true
        stdin_open: true

    nginx:
        image: nginx:stable-alpine3.23
        container_name: nginx
        depends_on:
            - app
        ports:
            - "${NGINX_PORT}:80"
        networks:
            - ddd-in-laravel-skeleton
        volumes:
            - ../:/app:ro
            - ./sources/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
    ddd-in-laravel-skeleton:
        driver: bridge
